services:
  - type: web
    name: youtube-upload-bot
    env: python
    buildCommand: apt-get update -qq && apt-get install -y -qq ffmpeg && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
